### ISSUE TITLE
KOM throws exception on ruby 2.4

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#126]
When using KPM with ruby `2.4`, we get the following exception:

```
/Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate killbill-client-2.1.0, because json-2.0.2 conflicts with json (< 2.0.0, >= 1.2.0) (Gem::ConflictError)
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/tenant_config.rb:3:in `<top (required)>'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:557:in `block in included'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:12:in `class_eval'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:12:in `included'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:5:in `include'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:5:in `<class:Cli>'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:4:in `<module:KPM>'
    from /Users/foo/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:3:in `<top (required)>'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/foo/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

It seems like the fix may be related to [this one](https://github.com/killbill/killbill-client-ruby/commit/d7cae1c1de57d0a2b643c98d90c6d43a3e8eaf77).

Also removing the following require `json` makes it work:

```
diff --git a/kpm/lib/kpm/tenant_config.rb b/kpm/lib/kpm/tenant_config.rb
index 94f2867..6584034 100644
--- a/kpm/lib/kpm/tenant_config.rb
+++ b/kpm/lib/kpm/tenant_config.rb
@@ -1,5 +1,5 @@
 require 'tmpdir'
-require 'json'
+#require 'json'
```

**Comment by pierre** [comment]
@sbrossie Is it still happening? I'm unable to reproduce it.

**Comment by sbrossie** [comment]
@pierre Yep, i am still seeing the issue:

```
> ~/Src/killbill/killbill-cloud/kpm(work-for-release-0.19.x)$ git log | head -1
commit 7e00ff8fcf0179933a255478b5dd35897f426514

> ~/Src/killbill/killbill-cloud/kpm(work-for-release-0.19.x)$ rvm list

rvm rubies
   ....
=* ruby-2.4.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

> ~/Src/killbill/killbill-cloud/kpm(work-for-release-0.19.x)$ bundle install
Using rake 10.5.0
Using bundler 1.16.1
Using diff-lcs 1.1.3
Using highline 1.6.21
Using killbill-client 1.12.1
Using rubyzip 1.2.1
Using thor 0.19.4
Using kpm 0.6.5 from source at `.`
Using rspec-core 2.12.2
Using rspec-expectations 2.12.1
Using rspec-mocks 2.12.2
Using rspec 2.12.0
Bundle complete! 3 Gemfile dependencies, 12 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

> ~/Src/killbill/killbill-cloud/kpm(work-for-release-0.19.x)$  bin/kpm --help
/Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate killbill-client-2.1.0, because json-2.0.2 conflicts with json (< 2.0.0, >= 1.2.0) (Gem::ConflictError)
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/tenant_config.rb:3:in `<top (required)>'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:557:in `block in included'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:12:in `class_eval'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/tasks.rb:12:in `included'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:5:in `include'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:5:in `<class:Cli>'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:4:in `<module:KPM>'
	from /Users/sbrossier/Src/killbill/killbill-cloud/kpm/lib/kpm/cli.rb:3:in `<top (required)>'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sbrossier/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/kpm:6:in `<main>'
```

**Comment by pierre** [comment]
> ~/Src/killbill/killbill-cloud/kpm(work-for-release-0.19.x)$ git log | head -1
commit 7e00ff8fcf0179933a255478b5dd35897f426514

Your repo is a bit old, can you pull the latest? That being said, I'm not sure it will make a difference.

I was on ruby-2.4.0 but I still cannot reproduce the issue with a fresh installation of `ruby 2.4.1p111` 😞 

Maybe remove your `Gemfile.lock` and try again?
