### ISSUE TITLE
Docker image creation seems post merge from work-for-release-0.19.x

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-cloud#130]
From [latest master](https://github.com/killbill/killbill-cloud/commit/145d816ab82f6875b42547d2f60914b1cecde5d1) following merge from `work-for-release-0.19.x`, building an image now leads to following exception:

```
Permission denied - /var/lib/tomcat
org/jruby/RubyDir.java:458:in `mkdir'
/var/lib/jruby/lib/ruby/1.9/fileutils.rb:247:in `fu_mkdir'
/var/lib/jruby/lib/ruby/1.9/fileutils.rb:221:in `mkdir_p'
org/jruby/RubyArray.java:1693:in `reverse_each'
/var/lib/jruby/lib/ruby/1.9/fileutils.rb:219:in `mkdir_p'
org/jruby/RubyArray.java:1613:in `each'
/var/lib/jruby/lib/ruby/1.9/fileutils.rb:205:in `mkdir_p'
/var/lib/jruby/lib/ruby/gems/shared/gems/kpm-0.5.3/lib/kpm/base_artifact.rb:98:in `pull_and_put_in_place'
/var/lib/jruby/lib/ruby/gems/shared/gems/kpm-0.5.3/lib/kpm/base_artifact.rb:40:in `pull'
/var/lib/jruby/lib/ruby/gems/shared/gems/kpm-0.5.3/lib/kpm/base_installer.rb:28:in `install_killbill_server'
/var/lib/jruby/lib/ruby/gems/shared/gems/kpm-0.5.3/lib/kpm/tasks.rb:78:in `pull_kb_server_war'
/var/lib/jruby/lib/ruby/gems/shared/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/var/lib/jruby/lib/ruby/gems/shared/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/jruby/lib/ruby/gems/shared/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/var/lib/jruby/lib/ruby/gems/shared/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/var/lib/jruby/lib/ruby/gems/shared/gems/kpm-0.5.3/bin/kpm:6:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/var/lib/jruby/bin/kpm:23:in `(root)'
The command '/bin/sh -c kpm pull_kb_server_war --destination=/var/lib/tomcat/webapps/ROOT.war --bundles_dir=/var/lib/killbill/bundles $KILLBILL_VERSION' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by pierre** [comment]
I wasn't able to reproduce it using the following steps:

```
make -e TARGET=base -e VERSION=latest rebuild
make -e TARGET=killbill -e VERSION=latest rebuild
make -e TARGET=killbill -e VERSION=0.20.0 rebuild
```
