### ISSUE TITLE
Error while Install Kpm : "SSL_connect returned=1 errno=0 state=error: certificate verify failed"

### ISSUE THREAD

**Issue by Aarul5** [killbill/killbill-cloud#69]
When i try to insatll killbill using this command :  **kpm install**
i got this errror : **SSL_connect returned=1 errno=0 state=error: certificate verify failed**

```
SSL_connect returned=1 errno=0 state=error: certificate verify failed
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect'
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:852:in `start'
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:584:in `start'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/lib/kpm/tomcat_manager.rb:22:in `block in download'
C:/Ruby23/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/lib/kpm/tomcat_manager.rb:18:in `download'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/lib/kpm/installer.rb:86:in `install_tomcat'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/lib/kpm/installer.rb:60:in `install'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/lib/kpm/tasks.rb:40:in `install'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/kpm-0.4.0/bin/kpm:6:in `<top (required)>'
C:/Ruby23/bin/kpm:22:in `load'
C:/Ruby23/bin/kpm:22:in `<main>'
```

**Comment by pierre** [comment]
Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for setup issues.
